### ISSUE TITLE
GLIBC version was too new.

### ISSUE THREAD

**Issue by CallItTrue** [siobhan-saoirse/npcs-in-tf2#1]
Could you please provide a compiled version under GLIBC 2.36 or older? was running my server in Debian 12 and can't do much around the compiling:/

ldd (Debian GLIBC 2.36-9+deb12u9) 2.36

<FAILED> file "monster.ext.so": /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by .../tf/addons/sourcemod_coop/extensions/monster.ext.so)

**Comment by siobhan-saoirse** [comment]
Sorry... I didn't know I compiled using a newer version.
I'll figure it out
